export async function POST(request: Request) {
  try {
    const { trackUris, playlistName, accessToken } = await request.json()
    console.log('[save-playlist] token prefix:', accessToken?.slice(0, 15))

    if (!accessToken) {
      return Response.json(
        { error: "No Spotify session found — please sign in." },
        { status: 401 }
      )
    }

    if (!Array.isArray(trackUris) || trackUris.length === 0) {
      return Response.json({ error: "No tracks provided." }, { status: 400 })
    }

    const meRes = await fetch("https://api.spotify.com/v1/me", {
      headers: { Authorization: `Bearer ${accessToken}` },
    })
    if (!meRes.ok) {
      return Response.json({ error: `Failed to fetch user: ${meRes.status} | token: ${accessToken?.slice(0, 15)} | len: ${accessToken?.length}` }, { status: 502 })
    }
    const meData = await meRes.json()
    const userId = meData.id
    console.log('[save-playlist] userId:', userId)

    const createRes = await fetch("https://api.spotify.com/v1/me/playlists", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: playlistName,
        public: true,
        description: "Generated by Q",
      }),
    })
    if (!createRes.ok) {
      const errText = await createRes.text()
      return Response.json({ error: `Failed to CREATE playlist: ${createRes.status} ${errText} | token: ${accessToken?.slice(0, 15)}` }, { status: 502 })
    }
    const createText = await createRes.text()
    console.log("[save-playlist] create playlist:", createRes.status, createText)
    const createData = JSON.parse(createText)
    console.log('[save-playlist] create playlist response:', JSON.stringify(createData))
    const playlistId = createData.id
    console.log("[save-playlist] playlistId:", playlistId)

    const SPOTIFY_URI_RE = /^spotify:track:[a-zA-Z0-9]{22}$/
    const filteredUris = trackUris.filter((u: string) => SPOTIFY_URI_RE.test(u))
    console.log(`[save-playlist] URI filter: ${filteredUris.length} valid of ${trackUris.length} received`)

    if (filteredUris.length === 0) {
      console.error("[save-playlist] all URIs failed validation:", trackUris.slice(0, 3))
      return Response.json(
        { error: "No valid Spotify track URIs — URIs must match spotify:track:<22 chars>. Check generate-playlist logs." },
        { status: 400 }
      )
    }

    const addBody = JSON.stringify({ uris: filteredUris })
    console.log("[save-playlist] add-tracks body:", addBody)

    const addRes = await fetch(`https://api.spotify.com/v1/playlists/${playlistId}/items`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: addBody,
    })
    const addText = await addRes.text()
    console.log("[save-playlist] add tracks:", addRes.status, addText)
    if (!addRes.ok) {
      if (addRes.status === 403) {
        console.error("[save-playlist] 403 full body:", addText)
      }
      return Response.json({ error: `Failed to ADD tracks: ${addRes.status} ${addText} | playlistId: ${playlistId} | uriCount: ${trackUris?.length} | token: ${accessToken?.slice(0, 15)}` }, { status: 502 })
    }

    const playlistUrl = createData.external_urls?.spotify ?? null
    return Response.json({ playlistUrl })
  } catch (err) {
    console.error("[save-playlist] error:", err)
    return Response.json({ error: "Failed to save playlist" }, { status: 500 })
  }
}
